# Generated by Django 6.0.2 on 2026-02-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at', 'display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('target_class', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=80)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=255)),
                ('mission', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('timings', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('step', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('age_group', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('daily_minutes', models.CharField(default='', max_length=40)),
                ('sheet_levels', models.CharField(default='', max_length=80)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=120)),
                ('photo_url', models.URLField(blank=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField()),
                ('awards', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('quote', models.TextField()),
                ('parent', models.CharField(max_length=120)),
                ('learner_class', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=80)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('preview_url', models.URLField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='core.programlevel')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
