# Generated by Django 6.0.2 on 2026-04-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('method', 'Method'), ('parent_corner', 'Parent Corner'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=40)),
                ('section_key', models.SlugField(max_length=80)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['page', 'display_order', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('page', 'section_key'), name='unique_page_section_key')],
            },
        ),
        migrations.CreateModel(
            name='PageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pagesection')),
            ],
            options={
                'ordering': ['section', 'display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
