# Generated by Django 6.0.2 on 2026-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagesection_pagesectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('method', 'Method'), ('admissions', 'Admissions'), ('parent_corner', 'Parent Corner'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=40),
        ),
    ]
